services:
  - type: web
    name: employee-orga-fullstack
    env: node
    plan: free
    region: oregon
    buildCommand: npm install && npm run build
    startCommand: npm run db:setup && npm run start
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: orga-db
          property: connectionString


databases:
  - name: orga-db
    plan: free
    region: oregon



